const jwt = require("jsonwebtoken");
const User = require("../models/User");
const axios = require("axios"); // Thêm thư viện này để gọi API
const { encryptString } = require("../utils/crypto");

function buildGitHubAuthorizeUrl(stateFromClient = "") {
  const clientId = process.env.GITHUB_CLIENT_ID;
  const frontendUrl = process.env.FRONTEND_URL || "http://localhost:3000";
  const redirectUri = `${frontendUrl}/auth/callback`;

  if (!clientId) {
    throw new Error("GITHUB_CLIENT_ID is not configured");
  }

  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: redirectUri,
    scope: "repo workflow",
  });

  if (stateFromClient && String(stateFromClient).trim()) {
    params.set("state", String(stateFromClient).trim());
  }

  return `https://github.com/login/oauth/authorize?${params.toString()}`;
}

function serializeUserProfile(userDoc) {
  const basePayload = {
    id: userDoc._id,
    username: userDoc.username,
    avatar: userDoc.avatar,
    role: userDoc.role,
    githubId: userDoc.githubId,
  };

  if (userDoc.role === "ADMIN") {
    return basePayload;
  }

  return {
    ...basePayload,
    tier: userDoc.tier,
    isFirstLogin: Boolean(userDoc.isFirstLogin),
    hasCustomGeminiKey: Boolean(userDoc.encryptedGeminiApiKey),
  };
}

const JWT_COOKIE_NAME = "jwt";
const JWT_COOKIE_OPTIONS = {
  httpOnly: true,
  secure: process.env.NODE_ENV === "production",
  sameSite: "strict",
  maxAge: 7 * 24 * 60 * 60 * 1000,
};

/**
 * GitHub OAuth Init Handler
 * @route GET /api/auth/github/login
 * @query state - single-use CSRF state generated by frontend
 */
const redirectToGitHubAuth = async (req, res) => {
  try {
    const state =
      typeof req.query?.state === "string" ? req.query.state.trim() : "";

    if (!state) {
      return res.status(400).json({
        error: "Missing OAuth state",
      });
    }

    const githubAuthUrl = buildGitHubAuthorizeUrl(state);
    return res.redirect(302, githubAuthUrl);
  } catch (error) {
    console.error("❌ GitHub auth init error:", error.message);
    return res.status(500).json({
      error: "Failed to initialize GitHub authentication",
    });
  }
};

/**
 * GitHub OAuth Callback Handler (Bảo mật chuẩn DevSecOps)
 * @route POST /api/auth/github/callback
 * @body {string} code - GitHub authorization code từ Frontend
 */
const handleGitHubCallback = async (req, res, next) => {
  try {
    const { code, state } = req.body;

    console.log("[OAuth Callback] Incoming exchange request", {
      hasCode: Boolean(code),
      codeLength: typeof code === "string" ? code.length : 0,
      codePreview:
        typeof code === "string" && code.length > 8
          ? `${code.slice(0, 4)}...${code.slice(-4)}`
          : code || null,
      hasState: Boolean(state),
      stateLength: typeof state === "string" ? state.length : 0,
      statePreview:
        typeof state === "string" && state.length > 8
          ? `${state.slice(0, 4)}...${state.slice(-4)}`
          : state || null,
    });

    if (!code) {
      return res
        .status(400)
        .json({ error: "Missing GitHub authorization code" });
    }

    // Bước 1: Backend tự mang "code" đi đổi lấy "access_token" từ GitHub
    const tokenResponse = await axios.post(
      "https://github.com/login/oauth/access_token",
      {
        client_id: process.env.GITHUB_CLIENT_ID,
        client_secret: process.env.GITHUB_CLIENT_SECRET,
        code: code,
      },
      {
        headers: { Accept: "application/json" },
      },
    );

    console.log("[OAuth Callback] GitHub token exchange response", {
      status: tokenResponse.status,
      hasAccessToken: Boolean(tokenResponse.data?.access_token),
      scope: tokenResponse.data?.scope,
      tokenType: tokenResponse.data?.token_type,
      error: tokenResponse.data?.error,
      errorDescription: tokenResponse.data?.error_description,
      errorUri: tokenResponse.data?.error_uri,
    });

    const accessToken = tokenResponse.data.access_token;
    if (!accessToken) {
      console.error("[OAuth Callback] GitHub token exchange failed", {
        error: tokenResponse.data?.error,
        errorDescription: tokenResponse.data?.error_description,
        rawData: tokenResponse.data,
      });
      return res
        .status(401)
        .json({ error: "Invalid code or GitHub API error" });
    }

    // Bước 2: Dùng access_token đó gọi API lấy thông tin Profile thật của user
    const userResponse = await axios.get("https://api.github.com/user", {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });

    // Dữ liệu SẠCH 100% lấy trực tiếp từ máy chủ GitHub
    const githubData = userResponse.data;

    const encryptedAccessToken = encryptString(accessToken);

    // Bước 3: Find or create user trong MongoDB
    let user = await User.findOne({ githubId: githubData.id.toString() });

    if (user) {
      user.githubAccessToken = encryptedAccessToken;
      user.lastLogin = new Date();
      user.avatar = githubData.avatar_url;
      user.username = githubData.login;
      if (user.role === "ADMIN") {
        user.tier = "PRO";
        user.isFirstLogin = false;
      }
    } else {
      user = new User({
        githubId: githubData.id.toString(),
        username: githubData.login,
        avatar: githubData.avatar_url,
        githubAccessToken: encryptedAccessToken,
        role: "USER", // Mặc định role
        tier: "FREE",
        analyzeCount: 0,
        lastResetDate: new Date(),
        isFirstLogin: true,
        lastLogin: new Date(),
      });
    }

    await user.save();
    console.log(`✅ User ${user.username} authenticated securely`);

    // Bước 4: Tạo JWT nội bộ
    const token = jwt.sign(
      { userId: user._id, role: user.role, tier: user.tier },
      process.env.JWT_SECRET,
      { expiresIn: "7d" },
    );

    console.log("Cookie options applied:", JWT_COOKIE_OPTIONS);
    res.cookie(JWT_COOKIE_NAME, token, JWT_COOKIE_OPTIONS);

    res.status(200).json({
      success: true,
      user: serializeUserProfile(user),
    });
  } catch (error) {
    console.error("❌ GitHub callback error (verbose):", {
      message: error.message,
      status: error.response?.status,
      responseData: error.response?.data,
      stack: error.stack,
    });
    res.status(500).json({ error: "GitHub authentication failed securely" });
  }
};

/**
 * Logout current user by clearing JWT cookie
 * @route POST /api/auth/logout
 */
const logoutUser = async (req, res) => {
  try {
    res.clearCookie(JWT_COOKIE_NAME, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "strict",
    });

    return res.status(200).json({
      success: true,
      message: "Logged out successfully",
    });
  } catch (error) {
    return res.status(500).json({
      error: "Failed to logout",
    });
  }
};

/**
 * Get Current User Profile
 * @route GET /api/auth/profile
 * @headers Authorization: Bearer <token>
 */
const getUserProfile = async (req, res) => {
  try {
    const user = await User.findById(req.user.userId).select(
      "_id username avatar role tier isFirstLogin githubId encryptedGeminiApiKey",
    );

    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    res.status(200).json({
      success: true,
      user: serializeUserProfile(user),
    });
  } catch (error) {
    console.error("Error fetching user profile:", error.message);
    res.status(500).json({
      error: "Failed to fetch user profile",
    });
  }
};

module.exports = {
  redirectToGitHubAuth,
  handleGitHubCallback,
  getUserProfile,
  logoutUser,
};
